         // try - catch method
// try { 
    
// } catch (error) {
    
// }

const username = "sai laxman"

try {
    console.log(myname);
    
} catch (error) {
    console.log(error.name);
    console.log(error.message);
    console.log(" got error");
}
console.log(username);